services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
  redis:
    container_name: redis
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
  adminer:
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
  uptimekuma:
    container_name: uptimekuma
    networks:
      - inception
    depends_on:
      - nginx
      - mariadb
      - wordpress
      - redis
      - adminer
    build:
      context: requirements/bonus/uptimekuma
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cauvray/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cauvray/data/mariadb
  uptimekuma:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cauvray/data/uptimekuma

networks:
  inception:
    name: inception
    driver: bridge
